# This config is a STUB! This should never be generated.
# Use the default lua config from https://github.com/hyprwm/Hyprland/blob/main/example/hyprland.lua



$mainMod = SUPER
$terminal = kitty
$fileManager = dolphin
$menu = rofi -show run

monitor = eDP-1,1920x1080@60,0x0,1

bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5

bind = SUPER SHIFT, 1, movetoworkspace, 1
bind = SUPER SHIFT, 2, movetoworkspace, 2
bind = SUPER SHIFT, 3, movetoworkspace, 3
bind = SUPER SHIFT, 4, movetoworkspace, 4
bind = $mainMod, C, killactive,
bind = $mainMod, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, V, togglefloating,
bind = $mainMod, R, exec, $menu
bind = SUPER, Q, exec, kitty
bind = SUPER, D, exec, rofi -show drun
bind = ALT, TAB, cyclenext
bind = ALT, TAB, bringactivetotop
bind = SUPER, B, exec, gtk-launch google-chrome
bind = SUPER, M, exec, hyprpanel t mediamenu
bind = , Insert, exec, grim -g "$(slurp)" ~/Pictures/Screenshots/$(date +'%Y-%m-%d_%H-%M-%S').png
bind = SUPER, V, togglefloating
bind = SUPER, T, togglefloating

bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow

env = mesa_glthread,true
env = __GL_THREADED_OPTIMIZATIONS,1


exec-once = fcitx5
exec-once = waybar
exec-once = swww init
exec-once = fcitx5
exec-once = hyprpaper
exec-once = swaybg -i /home/joeyjun/Pictures/peakpx.jpg -m fill
exec-once = swaync
#exec-once = hyprpanel
exec-once = awww-daemon
exec-once = cava -p ~/.config/cava/config
exec-once = waypaper --restore


decoration {
    rounding = 12

    blur {
        enabled = false
        size = 10
        passes = 4
        vibrancy = 0.2
    }
    
    active_opacity = 1
    inactive_opacity = 1
}

exec-once = swaybg -i /home/joeyjun/Pictures/peakpx.jpg -m fill

animations {
    enabled = yes

    bezier = ultraSmooth, 0.15, 0.85, 0.15, 1.02

    animation = windows, 1, 10, ultraSmooth
    animation = windowsIn, 1, 8, ultraSmooth, popin 88%
    animation = windowsOut, 1, 8, ultraSmooth, popin 88%

    animation = border, 1, 10, ultraSmooth
    animation = fade, 1, 10, ultraSmooth
    animation = workspaces, 1, 10, ultraSmooth
    animation = specialWorkspace, 1, 10, ultraSmooth
}

cursor {
    no_hardware_cursors = false
}

general {
    border_size = 2
    gaps_in = 2
    gaps_out = 10
    extend_border_grab_area = 15   
    resize_on_border = true
}
